import { defineConfig } from 'orval';

export default defineConfig({
	graphbit: {
		input: 'https://dev-platform-api.graphbit.ai/openapi.json',
		output: {
			client: 'react-query',
			mode: 'single',
			target: './src/generated/graphbit.ts',
			httpClient: 'axios',
			override: {
				query: {
					useQuery: true,
					useMutation: true,
					useSuspenseQuery: true,
				},
				mutator: {
					path: './src/services/api-client.ts',
					name: 'customInstance',
				},
				header: (info) => [
					`Generated by orval 🍺`,
					`Do not edit manually.`,
					...(info.title ? [info.title] : []),
					...(info.description ? [info.description] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
					'eslint-disable',
				],
			},
		},
	},
});
